import { ILayer } from "@layerhub-io/types"

export const SecondLevelMenus = ["FontFamily"]
export const FirstLevelMenus = ["Background"]

export enum SubMenuType {
  FONT_FAMILY = "FontFamily",
  BACKGROUND = "Background",
  COLOR = "Color",
  // ANIMATIONS = "Animations",
  // EFFECTS = "Effects",
}

export const SAMPLE_TEMPLATES = []

export const editorFonts = [
  {
    name: "Roboto",
    preview:
      "https://font-public.canva.com/YACgEev4gKc/0/thumbnail3539468006015936417.786a5ed94cf61f05978893c9088a06ea.png",
  },
  {
    name: "Quicksand",
    preview:
      "https://font-public.canva.com/YADWjpfPmdk/0/thumbnail1564020220251902443.bc4d1dede1fc33ec1e227ccfbc723b00.png",
  },

  {
    name: "Josefin Sans",
    preview:
      "https://font-public.canva.com/YADWjoIs6hY/0/thumbnail5311368174505054542.97ad47e884b96eb86f0a0f6b9abb0e61.png",
  },
  {
    name: "Arimo",
    preview:
      "https://font-public.canva.com/YACgEZ1cb1Q/0/thumbnail2753710016227887457.6dfe783f5d32581a0de7b11c49badc89.png",
  },
  {
    name: "Open Sans",
    preview:
      "https://font-public.canva.com/YAD7QhG2T6o/0/thumbnail4397746033903160930.50a02b6e1eabffa186ed7d1592726fe7.png",
  },
]

export const gradients = [
  {
    angle: 0,
    colors: ["#00c3ff", "#ffff1c"], //linear-gradient(to right, #00c3ff, #ffff1c)
  },
  {
    angle: 0,
    colors: ["#8e2de2", "#4a00e0"], //linear-gradient(to right, #00c3ff, #ffff1c)
  },
  {
    angle: 0,
    colors: ["#c0392b", "#8e44ad"], //linear-gradient(to right, #00c3ff, #ffff1c)
  },
  {
    angle: 0,
    colors: ["#ff00cc", "#333399"], //linear-gradient(to right, #00c3ff, #ffff1c)
  },
  {
    angle: 0,
    colors: ["#ff4b1f", "#1fddff"], //linear-gradient(to right, #00c3ff, #ffff1c)
  },
  {
    angle: 0,
    colors: ["#6a3093", "#a044ff"], //linear-gradient(to right, #00c3ff, #ffff1c)
  },
  {
    angle: 0,
    colors: ["#fc00ff", "#00dbde"], //linear-gradient(to right, #00c3ff, #ffff1c)
  },
  {
    angle: 0,
    colors: ["#ff0084", "#33001b"], //linear-gradient(to right, #00c3ff, #ffff1c)
  },
  {
    angle: 0,
    colors: ["#43cea2", "#185a9d"], //linear-gradient(to right, #00c3ff, #ffff1c)
  },
]

export const FONT_SIZES = Array.from({ length: 90 }, (_, i) => ({
  value: 8 + i, // [8, 9, ..., 97]
}))

export const SAMPLE_FONTS = [
  {
    id: "font_roboto_regular",
    family: "Roboto",
    full_name: "Roboto Regular",
    postscript_name: "Roboto",
    preview: "/editor/fonts/google/previews/roboto-regular.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/roboto/roboto-regular.ttf",
    category: "sans-serif",
  },
  {
    id: "font_roboto_600",
    family: "Roboto",
    full_name: "Roboto SemiBold",
    postscript_name: "Roboto-SemiBold",
    preview: "/editor/fonts/google/previews/roboto-600.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/roboto/roboto-600.ttf",
    category: "sans-serif",
  },
  {
    id: "font_roboto_700",
    family: "Roboto",
    full_name: "Roboto Bold",
    postscript_name: "Roboto-Bold",
    preview: "/editor/fonts/google/previews/roboto-700.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/roboto/roboto-700.ttf",
    category: "sans-serif",
  },
  {
    id: "font_open-sans_regular",
    family: "Open Sans",
    full_name: "Open Sans Regular",
    postscript_name: "OpenSans",
    preview: "/editor/fonts/google/previews/open-sans-regular.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/open-sans/open-sans-regular.ttf",
    category: "sans-serif",
  },
  {
    id: "font_open-sans_600",
    family: "Open Sans",
    full_name: "Open Sans SemiBold",
    postscript_name: "OpenSans-SemiBold",
    preview: "/editor/fonts/google/previews/open-sans-600.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/open-sans/open-sans-600.ttf",
    category: "sans-serif",
  },
  {
    id: "font_open-sans_700",
    family: "Open Sans",
    full_name: "Open Sans Bold",
    postscript_name: "OpenSans-Bold",
    preview: "/editor/fonts/google/previews/open-sans-700.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/open-sans/open-sans-700.ttf",
    category: "sans-serif",
  },
  {
    id: "font_noto-sans-jp_regular",
    family: "Noto Sans JP",
    full_name: "Noto Sans JP Regular",
    postscript_name: "NotoSansJP",
    preview: "/editor/fonts/google/previews/noto-sans-jp-regular.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/noto-sans-jp/noto-sans-jp-regular.ttf",
    category: "sans-serif",
  },
  {
    id: "font_noto-sans-jp_600",
    family: "Noto Sans JP",
    full_name: "Noto Sans JP SemiBold",
    postscript_name: "NotoSansJP-SemiBold",
    preview: "/editor/fonts/google/previews/noto-sans-jp-600.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/noto-sans-jp/noto-sans-jp-600.ttf",
    category: "sans-serif",
  },
  {
    id: "font_noto-sans-jp_700",
    family: "Noto Sans JP",
    full_name: "Noto Sans JP Bold",
    postscript_name: "NotoSansJP-Bold",
    preview: "/editor/fonts/google/previews/noto-sans-jp-700.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/noto-sans-jp/noto-sans-jp-700.ttf",
    category: "sans-serif",
  },
  {
    id: "font_montserrat_regular",
    family: "Montserrat",
    full_name: "Montserrat Regular",
    postscript_name: "Montserrat",
    preview: "/editor/fonts/google/previews/montserrat-regular.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/montserrat/montserrat-regular.ttf",
    category: "sans-serif",
  },
  {
    id: "font_montserrat_600",
    family: "Montserrat",
    full_name: "Montserrat SemiBold",
    postscript_name: "Montserrat-SemiBold",
    preview: "/editor/fonts/google/previews/montserrat-600.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/montserrat/montserrat-600.ttf",
    category: "sans-serif",
  },
  {
    id: "font_montserrat_700",
    family: "Montserrat",
    full_name: "Montserrat Bold",
    postscript_name: "Montserrat-Bold",
    preview: "/editor/fonts/google/previews/montserrat-700.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/montserrat/montserrat-700.ttf",
    category: "sans-serif",
  },
  {
    id: "font_inter_regular",
    family: "Inter",
    full_name: "Inter Regular",
    postscript_name: "Inter",
    preview: "/editor/fonts/google/previews/inter-regular.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/inter/inter-regular.ttf",
    category: "sans-serif",
  },
  {
    id: "font_inter_600",
    family: "Inter",
    full_name: "Inter SemiBold",
    postscript_name: "Inter-SemiBold",
    preview: "/editor/fonts/google/previews/inter-600.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/inter/inter-600.ttf",
    category: "sans-serif",
  },
  {
    id: "font_inter_700",
    family: "Inter",
    full_name: "Inter Bold",
    postscript_name: "Inter-Bold",
    preview: "/editor/fonts/google/previews/inter-700.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/inter/inter-700.ttf",
    category: "sans-serif",
  },
  {
    id: "font_poppins_regular",
    family: "Poppins",
    full_name: "Poppins Regular",
    postscript_name: "Poppins",
    preview: "/editor/fonts/google/previews/poppins-regular.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/poppins/poppins-regular.ttf",
    category: "sans-serif",
  },
  {
    id: "font_poppins_600",
    family: "Poppins",
    full_name: "Poppins SemiBold",
    postscript_name: "Poppins-SemiBold",
    preview: "/editor/fonts/google/previews/poppins-600.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/poppins/poppins-600.ttf",
    category: "sans-serif",
  },
  {
    id: "font_poppins_700",
    family: "Poppins",
    full_name: "Poppins Bold",
    postscript_name: "Poppins-Bold",
    preview: "/editor/fonts/google/previews/poppins-700.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/poppins/poppins-700.ttf",
    category: "sans-serif",
  },
  {
    id: "font_roboto-condensed_regular",
    family: "Roboto Condensed",
    full_name: "Roboto Condensed Regular",
    postscript_name: "RobotoCondensed",
    preview: "/editor/fonts/google/previews/roboto-condensed-regular.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/roboto-condensed/roboto-condensed-regular.ttf",
    category: "sans-serif",
  },
  {
    id: "font_roboto-condensed_600",
    family: "Roboto Condensed",
    full_name: "Roboto Condensed SemiBold",
    postscript_name: "RobotoCondensed-SemiBold",
    preview: "/editor/fonts/google/previews/roboto-condensed-600.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/roboto-condensed/roboto-condensed-600.ttf",
    category: "sans-serif",
  },
  {
    id: "font_roboto-condensed_700",
    family: "Roboto Condensed",
    full_name: "Roboto Condensed Bold",
    postscript_name: "RobotoCondensed-Bold",
    preview: "/editor/fonts/google/previews/roboto-condensed-700.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/roboto-condensed/roboto-condensed-700.ttf",
    category: "sans-serif",
  },
  {
    id: "font_oswald_regular",
    family: "Oswald",
    full_name: "Oswald Regular",
    postscript_name: "Oswald",
    preview: "/editor/fonts/google/previews/oswald-regular.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/oswald/oswald-regular.ttf",
    category: "sans-serif",
  },
  {
    id: "font_oswald_600",
    family: "Oswald",
    full_name: "Oswald SemiBold",
    postscript_name: "Oswald-SemiBold",
    preview: "/editor/fonts/google/previews/oswald-600.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/oswald/oswald-600.ttf",
    category: "sans-serif",
  },
  {
    id: "font_oswald_700",
    family: "Oswald",
    full_name: "Oswald Bold",
    postscript_name: "Oswald-Bold",
    preview: "/editor/fonts/google/previews/oswald-700.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/oswald/oswald-700.ttf",
    category: "sans-serif",
  },
  {
    id: "font_noto-sans_regular",
    family: "Noto Sans",
    full_name: "Noto Sans Regular",
    postscript_name: "NotoSans",
    preview: "/editor/fonts/google/previews/noto-sans-regular.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/noto-sans/noto-sans-regular.ttf",
    category: "sans-serif",
  },
  {
    id: "font_noto-sans_600",
    family: "Noto Sans",
    full_name: "Noto Sans SemiBold",
    postscript_name: "NotoSans-SemiBold",
    preview: "/editor/fonts/google/previews/noto-sans-600.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/noto-sans/noto-sans-600.ttf",
    category: "sans-serif",
  },
  {
    id: "font_noto-sans_700",
    family: "Noto Sans",
    full_name: "Noto Sans Bold",
    postscript_name: "NotoSans-Bold",
    preview: "/editor/fonts/google/previews/noto-sans-700.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/noto-sans/noto-sans-700.ttf",
    category: "sans-serif",
  },
  {
    id: "font_raleway_regular",
    family: "Raleway",
    full_name: "Raleway Regular",
    postscript_name: "Raleway",
    preview: "/editor/fonts/google/previews/raleway-regular.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/raleway/raleway-regular.ttf",
    category: "sans-serif",
  },
  {
    id: "font_raleway_600",
    family: "Raleway",
    full_name: "Raleway SemiBold",
    postscript_name: "Raleway-SemiBold",
    preview: "/editor/fonts/google/previews/raleway-600.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/raleway/raleway-600.ttf",
    category: "sans-serif",
  },
  {
    id: "font_raleway_700",
    family: "Raleway",
    full_name: "Raleway Bold",
    postscript_name: "Raleway-Bold",
    preview: "/editor/fonts/google/previews/raleway-700.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/raleway/raleway-700.ttf",
    category: "sans-serif",
  },
  {
    id: "font_playfair-display_regular",
    family: "Playfair Display",
    full_name: "Playfair Display Regular",
    postscript_name: "PlayfairDisplay",
    preview: "/editor/fonts/google/previews/playfair-display-regular.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/playfair-display/playfair-display-regular.ttf",
    category: "serif",
  },
  {
    id: "font_playfair-display_600",
    family: "Playfair Display",
    full_name: "Playfair Display SemiBold",
    postscript_name: "PlayfairDisplay-SemiBold",
    preview: "/editor/fonts/google/previews/playfair-display-600.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/playfair-display/playfair-display-600.ttf",
    category: "serif",
  },
  {
    id: "font_playfair-display_700",
    family: "Playfair Display",
    full_name: "Playfair Display Bold",
    postscript_name: "PlayfairDisplay-Bold",
    preview: "/editor/fonts/google/previews/playfair-display-700.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/playfair-display/playfair-display-700.ttf",
    category: "serif",
  },
  {
    id: "font_merriweather_regular",
    family: "Merriweather",
    full_name: "Merriweather Regular",
    postscript_name: "Merriweather",
    preview: "/editor/fonts/google/previews/merriweather-regular.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/merriweather/merriweather-regular.ttf",
    category: "serif",
  },
  {
    id: "font_merriweather_600",
    family: "Merriweather",
    full_name: "Merriweather SemiBold",
    postscript_name: "Merriweather-SemiBold",
    preview: "/editor/fonts/google/previews/merriweather-600.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/merriweather/merriweather-600.ttf",
    category: "serif",
  },
  {
    id: "font_merriweather_700",
    family: "Merriweather",
    full_name: "Merriweather Bold",
    postscript_name: "Merriweather-Bold",
    preview: "/editor/fonts/google/previews/merriweather-700.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/merriweather/merriweather-700.ttf",
    category: "serif",
  },
  {
    id: "font_roboto-slab_regular",
    family: "Roboto Slab",
    full_name: "Roboto Slab Regular",
    postscript_name: "RobotoSlab",
    preview: "/editor/fonts/google/previews/roboto-slab-regular.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/roboto-slab/roboto-slab-regular.ttf",
    category: "serif",
  },
  {
    id: "font_roboto-slab_600",
    family: "Roboto Slab",
    full_name: "Roboto Slab SemiBold",
    postscript_name: "RobotoSlab-SemiBold",
    preview: "/editor/fonts/google/previews/roboto-slab-600.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/roboto-slab/roboto-slab-600.ttf",
    category: "serif",
  },
  {
    id: "font_roboto-slab_700",
    family: "Roboto Slab",
    full_name: "Roboto Slab Bold",
    postscript_name: "RobotoSlab-Bold",
    preview: "/editor/fonts/google/previews/roboto-slab-700.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/roboto-slab/roboto-slab-700.ttf",
    category: "serif",
  },
  {
    id: "font_lora_regular",
    family: "Lora",
    full_name: "Lora Regular",
    postscript_name: "Lora",
    preview: "/editor/fonts/google/previews/lora-regular.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/lora/lora-regular.ttf",
    category: "serif",
  },
  {
    id: "font_lora_600",
    family: "Lora",
    full_name: "Lora SemiBold",
    postscript_name: "Lora-SemiBold",
    preview: "/editor/fonts/google/previews/lora-600.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/lora/lora-600.ttf",
    category: "serif",
  },
  {
    id: "font_lora_700",
    family: "Lora",
    full_name: "Lora Bold",
    postscript_name: "Lora-Bold",
    preview: "/editor/fonts/google/previews/lora-700.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/lora/lora-700.ttf",
    category: "serif",
  },
  {
    id: "font_noto-serif_regular",
    family: "Noto Serif",
    full_name: "Noto Serif Regular",
    postscript_name: "NotoSerif",
    preview: "/editor/fonts/google/previews/noto-serif-regular.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/noto-serif/noto-serif-regular.ttf",
    category: "serif",
  },
  {
    id: "font_noto-serif_600",
    family: "Noto Serif",
    full_name: "Noto Serif SemiBold",
    postscript_name: "NotoSerif-SemiBold",
    preview: "/editor/fonts/google/previews/noto-serif-600.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/noto-serif/noto-serif-600.ttf",
    category: "serif",
  },
  {
    id: "font_noto-serif_700",
    family: "Noto Serif",
    full_name: "Noto Serif Bold",
    postscript_name: "NotoSerif-Bold",
    preview: "/editor/fonts/google/previews/noto-serif-700.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/noto-serif/noto-serif-700.ttf",
    category: "serif",
  },
  {
    id: "font_ibm-plex-serif_regular",
    family: "IBM Plex Serif",
    full_name: "IBM Plex Serif Regular",
    postscript_name: "IBMPlexSerif",
    preview: "/editor/fonts/google/previews/ibm-plex-serif-regular.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/ibm-plex-serif/ibm-plex-serif-regular.ttf",
    category: "serif",
  },
  {
    id: "font_ibm-plex-serif_600",
    family: "IBM Plex Serif",
    full_name: "IBM Plex Serif SemiBold",
    postscript_name: "IBMPlexSerif-SemiBold",
    preview: "/editor/fonts/google/previews/ibm-plex-serif-600.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/ibm-plex-serif/ibm-plex-serif-600.ttf",
    category: "serif",
  },
  {
    id: "font_ibm-plex-serif_700",
    family: "IBM Plex Serif",
    full_name: "IBM Plex Serif Bold",
    postscript_name: "IBMPlexSerif-Bold",
    preview: "/editor/fonts/google/previews/ibm-plex-serif-700.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/ibm-plex-serif/ibm-plex-serif-700.ttf",
    category: "serif",
  },
  {
    id: "font_noto-serif-jp_regular",
    family: "Noto Serif JP",
    full_name: "Noto Serif JP Regular",
    postscript_name: "NotoSerifJP",
    preview: "/editor/fonts/google/previews/noto-serif-jp-regular.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/noto-serif-jp/noto-serif-jp-regular.ttf",
    category: "serif",
  },
  {
    id: "font_noto-serif-jp_600",
    family: "Noto Serif JP",
    full_name: "Noto Serif JP SemiBold",
    postscript_name: "NotoSerifJP-SemiBold",
    preview: "/editor/fonts/google/previews/noto-serif-jp-600.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/noto-serif-jp/noto-serif-jp-600.ttf",
    category: "serif",
  },
  {
    id: "font_noto-serif-jp_700",
    family: "Noto Serif JP",
    full_name: "Noto Serif JP Bold",
    postscript_name: "NotoSerifJP-Bold",
    preview: "/editor/fonts/google/previews/noto-serif-jp-700.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/noto-serif-jp/noto-serif-jp-700.ttf",
    category: "serif",
  },
  {
    id: "font_eb-garamond_regular",
    family: "EB Garamond",
    full_name: "EB Garamond Regular",
    postscript_name: "EBGaramond",
    preview: "/editor/fonts/google/previews/eb-garamond-regular.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/eb-garamond/eb-garamond-regular.ttf",
    category: "serif",
  },
  {
    id: "font_eb-garamond_600",
    family: "EB Garamond",
    full_name: "EB Garamond SemiBold",
    postscript_name: "EBGaramond-SemiBold",
    preview: "/editor/fonts/google/previews/eb-garamond-600.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/eb-garamond/eb-garamond-600.ttf",
    category: "serif",
  },
  {
    id: "font_eb-garamond_700",
    family: "EB Garamond",
    full_name: "EB Garamond Bold",
    postscript_name: "EBGaramond-Bold",
    preview: "/editor/fonts/google/previews/eb-garamond-700.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/eb-garamond/eb-garamond-700.ttf",
    category: "serif",
  },
  {
    id: "font_bitter_regular",
    family: "Bitter",
    full_name: "Bitter Regular",
    postscript_name: "Bitter",
    preview: "/editor/fonts/google/previews/bitter-regular.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/bitter/bitter-regular.ttf",
    category: "serif",
  },
  {
    id: "font_bitter_600",
    family: "Bitter",
    full_name: "Bitter SemiBold",
    postscript_name: "Bitter-SemiBold",
    preview: "/editor/fonts/google/previews/bitter-600.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/bitter/bitter-600.ttf",
    category: "serif",
  },
  {
    id: "font_bitter_700",
    family: "Bitter",
    full_name: "Bitter Bold",
    postscript_name: "Bitter-Bold",
    preview: "/editor/fonts/google/previews/bitter-700.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/bitter/bitter-700.ttf",
    category: "serif",
  },
  {
    id: "font_crimson-text_regular",
    family: "Crimson Text",
    full_name: "Crimson Text Regular",
    postscript_name: "CrimsonText",
    preview: "/editor/fonts/google/previews/crimson-text-regular.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/crimson-text/crimson-text-regular.ttf",
    category: "serif",
  },
  {
    id: "font_crimson-text_600",
    family: "Crimson Text",
    full_name: "Crimson Text SemiBold",
    postscript_name: "CrimsonText-SemiBold",
    preview: "/editor/fonts/google/previews/crimson-text-600.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/crimson-text/crimson-text-600.ttf",
    category: "serif",
  },
  {
    id: "font_crimson-text_700",
    family: "Crimson Text",
    full_name: "Crimson Text Bold",
    postscript_name: "CrimsonText-Bold",
    preview: "/editor/fonts/google/previews/crimson-text-700.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/crimson-text/crimson-text-700.ttf",
    category: "serif",
  },
  {
    id: "font_comfortaa_regular",
    family: "Comfortaa",
    full_name: "Comfortaa Regular",
    postscript_name: "Comfortaa",
    preview: "/editor/fonts/google/previews/comfortaa-regular.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/comfortaa/comfortaa-regular.ttf",
    category: "display",
  },
  {
    id: "font_comfortaa_600",
    family: "Comfortaa",
    full_name: "Comfortaa SemiBold",
    postscript_name: "Comfortaa-SemiBold",
    preview: "/editor/fonts/google/previews/comfortaa-600.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/comfortaa/comfortaa-600.ttf",
    category: "display",
  },
  {
    id: "font_comfortaa_700",
    family: "Comfortaa",
    full_name: "Comfortaa Bold",
    postscript_name: "Comfortaa-Bold",
    preview: "/editor/fonts/google/previews/comfortaa-700.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/comfortaa/comfortaa-700.ttf",
    category: "display",
  },
  {
    id: "font_baloo-2_regular",
    family: "Baloo 2",
    full_name: "Baloo 2 Regular",
    postscript_name: "Baloo2",
    preview: "/editor/fonts/google/previews/baloo-2-regular.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/baloo-2/baloo-2-regular.ttf",
    category: "display",
  },
  {
    id: "font_baloo-2_600",
    family: "Baloo 2",
    full_name: "Baloo 2 SemiBold",
    postscript_name: "Baloo2-SemiBold",
    preview: "/editor/fonts/google/previews/baloo-2-600.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/baloo-2/baloo-2-600.ttf",
    category: "display",
  },
  {
    id: "font_baloo-2_700",
    family: "Baloo 2",
    full_name: "Baloo 2 Bold",
    postscript_name: "Baloo2-Bold",
    preview: "/editor/fonts/google/previews/baloo-2-700.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/baloo-2/baloo-2-700.ttf",
    category: "display",
  },
  {
    id: "font_oxanium_regular",
    family: "Oxanium",
    full_name: "Oxanium Regular",
    postscript_name: "Oxanium",
    preview: "/editor/fonts/google/previews/oxanium-regular.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/oxanium/oxanium-regular.ttf",
    category: "display",
  },
  {
    id: "font_oxanium_600",
    family: "Oxanium",
    full_name: "Oxanium SemiBold",
    postscript_name: "Oxanium-SemiBold",
    preview: "/editor/fonts/google/previews/oxanium-600.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/oxanium/oxanium-600.ttf",
    category: "display",
  },
  {
    id: "font_oxanium_700",
    family: "Oxanium",
    full_name: "Oxanium Bold",
    postscript_name: "Oxanium-Bold",
    preview: "/editor/fonts/google/previews/oxanium-700.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/oxanium/oxanium-700.ttf",
    category: "display",
  },
  {
    id: "font_baloo-bhaijaan-2_regular",
    family: "Baloo Bhaijaan 2",
    full_name: "Baloo Bhaijaan 2 Regular",
    postscript_name: "BalooBhaijaan2",
    preview: "/editor/fonts/google/previews/baloo-bhaijaan-2-regular.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/baloo-bhaijaan-2/baloo-bhaijaan-2-regular.ttf",
    category: "display",
  },
  {
    id: "font_baloo-bhaijaan-2_600",
    family: "Baloo Bhaijaan 2",
    full_name: "Baloo Bhaijaan 2 SemiBold",
    postscript_name: "BalooBhaijaan2-SemiBold",
    preview: "/editor/fonts/google/previews/baloo-bhaijaan-2-600.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/baloo-bhaijaan-2/baloo-bhaijaan-2-600.ttf",
    category: "display",
  },
  {
    id: "font_baloo-bhaijaan-2_700",
    family: "Baloo Bhaijaan 2",
    full_name: "Baloo Bhaijaan 2 Bold",
    postscript_name: "BalooBhaijaan2-Bold",
    preview: "/editor/fonts/google/previews/baloo-bhaijaan-2-700.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/baloo-bhaijaan-2/baloo-bhaijaan-2-700.ttf",
    category: "display",
  },
  {
    id: "font_tektur_regular",
    family: "Tektur",
    full_name: "Tektur Regular",
    postscript_name: "Tektur",
    preview: "/editor/fonts/google/previews/tektur-regular.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/tektur/tektur-regular.ttf",
    category: "display",
  },
  {
    id: "font_tektur_600",
    family: "Tektur",
    full_name: "Tektur SemiBold",
    postscript_name: "Tektur-SemiBold",
    preview: "/editor/fonts/google/previews/tektur-600.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/tektur/tektur-600.ttf",
    category: "display",
  },
  {
    id: "font_tektur_700",
    family: "Tektur",
    full_name: "Tektur Bold",
    postscript_name: "Tektur-Bold",
    preview: "/editor/fonts/google/previews/tektur-700.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/tektur/tektur-700.ttf",
    category: "display",
  },
  {
    id: "font_gabarito_regular",
    family: "Gabarito",
    full_name: "Gabarito Regular",
    postscript_name: "Gabarito",
    preview: "/editor/fonts/google/previews/gabarito-regular.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/gabarito/gabarito-regular.ttf",
    category: "display",
  },
  {
    id: "font_gabarito_600",
    family: "Gabarito",
    full_name: "Gabarito SemiBold",
    postscript_name: "Gabarito-SemiBold",
    preview: "/editor/fonts/google/previews/gabarito-600.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/gabarito/gabarito-600.ttf",
    category: "display",
  },
  {
    id: "font_gabarito_700",
    family: "Gabarito",
    full_name: "Gabarito Bold",
    postscript_name: "Gabarito-Bold",
    preview: "/editor/fonts/google/previews/gabarito-700.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/gabarito/gabarito-700.ttf",
    category: "display",
  },
  {
    id: "font_grandstander_regular",
    family: "Grandstander",
    full_name: "Grandstander Regular",
    postscript_name: "Grandstander",
    preview: "/editor/fonts/google/previews/grandstander-regular.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/grandstander/grandstander-regular.ttf",
    category: "display",
  },
  {
    id: "font_grandstander_600",
    family: "Grandstander",
    full_name: "Grandstander SemiBold",
    postscript_name: "Grandstander-SemiBold",
    preview: "/editor/fonts/google/previews/grandstander-600.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/grandstander/grandstander-600.ttf",
    category: "display",
  },
  {
    id: "font_grandstander_700",
    family: "Grandstander",
    full_name: "Grandstander Bold",
    postscript_name: "Grandstander-Bold",
    preview: "/editor/fonts/google/previews/grandstander-700.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/grandstander/grandstander-700.ttf",
    category: "display",
  },
  {
    id: "font_lemonada_regular",
    family: "Lemonada",
    full_name: "Lemonada Regular",
    postscript_name: "Lemonada",
    preview: "/editor/fonts/google/previews/lemonada-regular.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/lemonada/lemonada-regular.ttf",
    category: "display",
  },
  {
    id: "font_lemonada_600",
    family: "Lemonada",
    full_name: "Lemonada SemiBold",
    postscript_name: "Lemonada-SemiBold",
    preview: "/editor/fonts/google/previews/lemonada-600.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/lemonada/lemonada-600.ttf",
    category: "display",
  },
  {
    id: "font_lemonada_700",
    family: "Lemonada",
    full_name: "Lemonada Bold",
    postscript_name: "Lemonada-Bold",
    preview: "/editor/fonts/google/previews/lemonada-700.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/lemonada/lemonada-700.ttf",
    category: "display",
  },
  {
    id: "font_museomoderno_regular",
    family: "MuseoModerno",
    full_name: "MuseoModerno Regular",
    postscript_name: "MuseoModerno",
    preview: "/editor/fonts/google/previews/museomoderno-regular.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/museomoderno/museomoderno-regular.ttf",
    category: "display",
  },
  {
    id: "font_museomoderno_600",
    family: "MuseoModerno",
    full_name: "MuseoModerno SemiBold",
    postscript_name: "MuseoModerno-SemiBold",
    preview: "/editor/fonts/google/previews/museomoderno-600.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/museomoderno/museomoderno-600.ttf",
    category: "display",
  },
  {
    id: "font_museomoderno_700",
    family: "MuseoModerno",
    full_name: "MuseoModerno Bold",
    postscript_name: "MuseoModerno-Bold",
    preview: "/editor/fonts/google/previews/museomoderno-700.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/museomoderno/museomoderno-700.ttf",
    category: "display",
  },
  {
    id: "font_shantell-sans_regular",
    family: "Shantell Sans",
    full_name: "Shantell Sans Regular",
    postscript_name: "ShantellSans",
    preview: "/editor/fonts/google/previews/shantell-sans-regular.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/shantell-sans/shantell-sans-regular.ttf",
    category: "display",
  },
  {
    id: "font_shantell-sans_600",
    family: "Shantell Sans",
    full_name: "Shantell Sans SemiBold",
    postscript_name: "ShantellSans-SemiBold",
    preview: "/editor/fonts/google/previews/shantell-sans-600.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/shantell-sans/shantell-sans-600.ttf",
    category: "display",
  },
  {
    id: "font_shantell-sans_700",
    family: "Shantell Sans",
    full_name: "Shantell Sans Bold",
    postscript_name: "ShantellSans-Bold",
    preview: "/editor/fonts/google/previews/shantell-sans-700.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/shantell-sans/shantell-sans-700.ttf",
    category: "display",
  },
  {
    id: "font_dancing-script_regular",
    family: "Dancing Script",
    full_name: "Dancing Script Regular",
    postscript_name: "DancingScript",
    preview: "/editor/fonts/google/previews/dancing-script-regular.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/dancing-script/dancing-script-regular.ttf",
    category: "handwriting",
  },
  {
    id: "font_dancing-script_600",
    family: "Dancing Script",
    full_name: "Dancing Script SemiBold",
    postscript_name: "DancingScript-SemiBold",
    preview: "/editor/fonts/google/previews/dancing-script-600.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/dancing-script/dancing-script-600.ttf",
    category: "handwriting",
  },
  {
    id: "font_dancing-script_700",
    family: "Dancing Script",
    full_name: "Dancing Script Bold",
    postscript_name: "DancingScript-Bold",
    preview: "/editor/fonts/google/previews/dancing-script-700.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/dancing-script/dancing-script-700.ttf",
    category: "handwriting",
  },
  {
    id: "font_caveat_regular",
    family: "Caveat",
    full_name: "Caveat Regular",
    postscript_name: "Caveat",
    preview: "/editor/fonts/google/previews/caveat-regular.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/caveat/caveat-regular.ttf",
    category: "handwriting",
  },
  {
    id: "font_caveat_600",
    family: "Caveat",
    full_name: "Caveat SemiBold",
    postscript_name: "Caveat-SemiBold",
    preview: "/editor/fonts/google/previews/caveat-600.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/caveat/caveat-600.ttf",
    category: "handwriting",
  },
  {
    id: "font_caveat_700",
    family: "Caveat",
    full_name: "Caveat Bold",
    postscript_name: "Caveat-Bold",
    preview: "/editor/fonts/google/previews/caveat-700.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/caveat/caveat-700.ttf",
    category: "handwriting",
  },
  {
    id: "font_merienda_regular",
    family: "Merienda",
    full_name: "Merienda Regular",
    postscript_name: "Merienda",
    preview: "/editor/fonts/google/previews/merienda-regular.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/merienda/merienda-regular.ttf",
    category: "handwriting",
  },
  {
    id: "font_merienda_600",
    family: "Merienda",
    full_name: "Merienda SemiBold",
    postscript_name: "Merienda-SemiBold",
    preview: "/editor/fonts/google/previews/merienda-600.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/merienda/merienda-600.ttf",
    category: "handwriting",
  },
  {
    id: "font_merienda_700",
    family: "Merienda",
    full_name: "Merienda Bold",
    postscript_name: "Merienda-Bold",
    preview: "/editor/fonts/google/previews/merienda-700.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/merienda/merienda-700.ttf",
    category: "handwriting",
  },
  {
    id: "font_mali_regular",
    family: "Mali",
    full_name: "Mali Regular",
    postscript_name: "Mali",
    preview: "/editor/fonts/google/previews/mali-regular.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/mali/mali-regular.ttf",
    category: "handwriting",
  },
  {
    id: "font_mali_600",
    family: "Mali",
    full_name: "Mali SemiBold",
    postscript_name: "Mali-SemiBold",
    preview: "/editor/fonts/google/previews/mali-600.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/mali/mali-600.ttf",
    category: "handwriting",
  },
  {
    id: "font_mali_700",
    family: "Mali",
    full_name: "Mali Bold",
    postscript_name: "Mali-Bold",
    preview: "/editor/fonts/google/previews/mali-700.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/mali/mali-700.ttf",
    category: "handwriting",
  },
  {
    id: "font_playpen-sans_regular",
    family: "Playpen Sans",
    full_name: "Playpen Sans Regular",
    postscript_name: "PlaypenSans",
    preview: "/editor/fonts/google/previews/playpen-sans-regular.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/playpen-sans/playpen-sans-regular.ttf",
    category: "handwriting",
  },
  {
    id: "font_playpen-sans_600",
    family: "Playpen Sans",
    full_name: "Playpen Sans SemiBold",
    postscript_name: "PlaypenSans-SemiBold",
    preview: "/editor/fonts/google/previews/playpen-sans-600.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/playpen-sans/playpen-sans-600.ttf",
    category: "handwriting",
  },
  {
    id: "font_playpen-sans_700",
    family: "Playpen Sans",
    full_name: "Playpen Sans Bold",
    postscript_name: "PlaypenSans-Bold",
    preview: "/editor/fonts/google/previews/playpen-sans-700.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/playpen-sans/playpen-sans-700.ttf",
    category: "handwriting",
  },
  {
    id: "font_edu-sa-beginner_regular",
    family: "Edu SA Beginner",
    full_name: "Edu SA Beginner Regular",
    postscript_name: "EduSABeginner",
    preview: "/editor/fonts/google/previews/edu-sa-beginner-regular.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/edu-sa-beginner/edu-sa-beginner-regular.ttf",
    category: "handwriting",
  },
  {
    id: "font_edu-sa-beginner_600",
    family: "Edu SA Beginner",
    full_name: "Edu SA Beginner SemiBold",
    postscript_name: "EduSABeginner-SemiBold",
    preview: "/editor/fonts/google/previews/edu-sa-beginner-600.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/edu-sa-beginner/edu-sa-beginner-600.ttf",
    category: "handwriting",
  },
  {
    id: "font_edu-sa-beginner_700",
    family: "Edu SA Beginner",
    full_name: "Edu SA Beginner Bold",
    postscript_name: "EduSABeginner-Bold",
    preview: "/editor/fonts/google/previews/edu-sa-beginner-700.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/edu-sa-beginner/edu-sa-beginner-700.ttf",
    category: "handwriting",
  },
  {
    id: "font_edu-tas-beginner_regular",
    family: "Edu TAS Beginner",
    full_name: "Edu TAS Beginner Regular",
    postscript_name: "EduTASBeginner",
    preview: "/editor/fonts/google/previews/edu-tas-beginner-regular.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/edu-tas-beginner/edu-tas-beginner-regular.ttf",
    category: "handwriting",
  },
  {
    id: "font_edu-tas-beginner_600",
    family: "Edu TAS Beginner",
    full_name: "Edu TAS Beginner SemiBold",
    postscript_name: "EduTASBeginner-SemiBold",
    preview: "/editor/fonts/google/previews/edu-tas-beginner-600.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/edu-tas-beginner/edu-tas-beginner-600.ttf",
    category: "handwriting",
  },
  {
    id: "font_edu-tas-beginner_700",
    family: "Edu TAS Beginner",
    full_name: "Edu TAS Beginner Bold",
    postscript_name: "EduTASBeginner-Bold",
    preview: "/editor/fonts/google/previews/edu-tas-beginner-700.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/edu-tas-beginner/edu-tas-beginner-700.ttf",
    category: "handwriting",
  },
  {
    id: "font_edu-nsw-act-foundation_regular",
    family: "Edu NSW ACT Foundation",
    full_name: "Edu NSW ACT Foundation Regular",
    postscript_name: "EduNSWACTFoundation",
    preview: "/editor/fonts/google/previews/edu-nsw-act-foundation-regular.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/edu-nsw-act-foundation/edu-nsw-act-foundation-regular.ttf",
    category: "handwriting",
  },
  {
    id: "font_edu-nsw-act-foundation_600",
    family: "Edu NSW ACT Foundation",
    full_name: "Edu NSW ACT Foundation SemiBold",
    postscript_name: "EduNSWACTFoundation-SemiBold",
    preview: "/editor/fonts/google/previews/edu-nsw-act-foundation-600.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/edu-nsw-act-foundation/edu-nsw-act-foundation-600.ttf",
    category: "handwriting",
  },
  {
    id: "font_edu-nsw-act-foundation_700",
    family: "Edu NSW ACT Foundation",
    full_name: "Edu NSW ACT Foundation Bold",
    postscript_name: "EduNSWACTFoundation-Bold",
    preview: "/editor/fonts/google/previews/edu-nsw-act-foundation-700.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/edu-nsw-act-foundation/edu-nsw-act-foundation-700.ttf",
    category: "handwriting",
  },
  {
    id: "font_edu-au-vic-wa-nt-hand_regular",
    family: "Edu AU VIC WA NT Hand",
    full_name: "Edu AU VIC WA NT Hand Regular",
    postscript_name: "EduAUVICWANTHand",
    preview: "/editor/fonts/google/previews/edu-au-vic-wa-nt-hand-regular.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/edu-au-vic-wa-nt-hand/edu-au-vic-wa-nt-hand-regular.ttf",
    category: "handwriting",
  },
  {
    id: "font_edu-au-vic-wa-nt-hand_600",
    family: "Edu AU VIC WA NT Hand",
    full_name: "Edu AU VIC WA NT Hand SemiBold",
    postscript_name: "EduAUVICWANTHand-SemiBold",
    preview: "/editor/fonts/google/previews/edu-au-vic-wa-nt-hand-600.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/edu-au-vic-wa-nt-hand/edu-au-vic-wa-nt-hand-600.ttf",
    category: "handwriting",
  },
  {
    id: "font_edu-au-vic-wa-nt-hand_700",
    family: "Edu AU VIC WA NT Hand",
    full_name: "Edu AU VIC WA NT Hand Bold",
    postscript_name: "EduAUVICWANTHand-Bold",
    preview: "/editor/fonts/google/previews/edu-au-vic-wa-nt-hand-700.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/edu-au-vic-wa-nt-hand/edu-au-vic-wa-nt-hand-700.ttf",
    category: "handwriting",
  },
  {
    id: "font_edu-vic-wa-nt-beginner_regular",
    family: "Edu VIC WA NT Beginner",
    full_name: "Edu VIC WA NT Beginner Regular",
    postscript_name: "EduVICWANTBeginner",
    preview: "/editor/fonts/google/previews/edu-vic-wa-nt-beginner-regular.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/edu-vic-wa-nt-beginner/edu-vic-wa-nt-beginner-regular.ttf",
    category: "handwriting",
  },
  {
    id: "font_edu-vic-wa-nt-beginner_600",
    family: "Edu VIC WA NT Beginner",
    full_name: "Edu VIC WA NT Beginner SemiBold",
    postscript_name: "EduVICWANTBeginner-SemiBold",
    preview: "/editor/fonts/google/previews/edu-vic-wa-nt-beginner-600.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/edu-vic-wa-nt-beginner/edu-vic-wa-nt-beginner-600.ttf",
    category: "handwriting",
  },
  {
    id: "font_edu-vic-wa-nt-beginner_700",
    family: "Edu VIC WA NT Beginner",
    full_name: "Edu VIC WA NT Beginner Bold",
    postscript_name: "EduVICWANTBeginner-Bold",
    preview: "/editor/fonts/google/previews/edu-vic-wa-nt-beginner-700.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/edu-vic-wa-nt-beginner/edu-vic-wa-nt-beginner-700.ttf",
    category: "handwriting",
  },
  {
    id: "font_roboto-mono_regular",
    family: "Roboto Mono",
    full_name: "Roboto Mono Regular",
    postscript_name: "RobotoMono",
    preview: "/editor/fonts/google/previews/roboto-mono-regular.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/roboto-mono/roboto-mono-regular.ttf",
    category: "monospace",
  },
  {
    id: "font_roboto-mono_600",
    family: "Roboto Mono",
    full_name: "Roboto Mono SemiBold",
    postscript_name: "RobotoMono-SemiBold",
    preview: "/editor/fonts/google/previews/roboto-mono-600.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/roboto-mono/roboto-mono-600.ttf",
    category: "monospace",
  },
  {
    id: "font_roboto-mono_700",
    family: "Roboto Mono",
    full_name: "Roboto Mono Bold",
    postscript_name: "RobotoMono-Bold",
    preview: "/editor/fonts/google/previews/roboto-mono-700.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/roboto-mono/roboto-mono-700.ttf",
    category: "monospace",
  },
  {
    id: "font_material-symbols-outlined_regular",
    family: "Material Symbols Outlined",
    full_name: "Material Symbols Outlined Regular",
    postscript_name: "MaterialSymbolsOutlined",
    preview: "/editor/fonts/google/previews/material-symbols-outlined-regular.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/material-symbols-outlined/material-symbols-outlined-regular.ttf",
    category: "monospace",
  },
  {
    id: "font_material-symbols-outlined_600",
    family: "Material Symbols Outlined",
    full_name: "Material Symbols Outlined SemiBold",
    postscript_name: "MaterialSymbolsOutlined-SemiBold",
    preview: "/editor/fonts/google/previews/material-symbols-outlined-600.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/material-symbols-outlined/material-symbols-outlined-600.ttf",
    category: "monospace",
  },
  {
    id: "font_material-symbols-outlined_700",
    family: "Material Symbols Outlined",
    full_name: "Material Symbols Outlined Bold",
    postscript_name: "MaterialSymbolsOutlined-Bold",
    preview: "/editor/fonts/google/previews/material-symbols-outlined-700.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/material-symbols-outlined/material-symbols-outlined-700.ttf",
    category: "monospace",
  },
  {
    id: "font_inconsolata_regular",
    family: "Inconsolata",
    full_name: "Inconsolata Regular",
    postscript_name: "Inconsolata",
    preview: "/editor/fonts/google/previews/inconsolata-regular.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/inconsolata/inconsolata-regular.ttf",
    category: "monospace",
  },
  {
    id: "font_inconsolata_600",
    family: "Inconsolata",
    full_name: "Inconsolata SemiBold",
    postscript_name: "Inconsolata-SemiBold",
    preview: "/editor/fonts/google/previews/inconsolata-600.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/inconsolata/inconsolata-600.ttf",
    category: "monospace",
  },
  {
    id: "font_inconsolata_700",
    family: "Inconsolata",
    full_name: "Inconsolata Bold",
    postscript_name: "Inconsolata-Bold",
    preview: "/editor/fonts/google/previews/inconsolata-700.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/inconsolata/inconsolata-700.ttf",
    category: "monospace",
  },
  {
    id: "font_material-symbols-rounded_regular",
    family: "Material Symbols Rounded",
    full_name: "Material Symbols Rounded Regular",
    postscript_name: "MaterialSymbolsRounded",
    preview: "/editor/fonts/google/previews/material-symbols-rounded-regular.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/material-symbols-rounded/material-symbols-rounded-regular.ttf",
    category: "monospace",
  },
  {
    id: "font_material-symbols-rounded_600",
    family: "Material Symbols Rounded",
    full_name: "Material Symbols Rounded SemiBold",
    postscript_name: "MaterialSymbolsRounded-SemiBold",
    preview: "/editor/fonts/google/previews/material-symbols-rounded-600.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/material-symbols-rounded/material-symbols-rounded-600.ttf",
    category: "monospace",
  },
  {
    id: "font_material-symbols-rounded_700",
    family: "Material Symbols Rounded",
    full_name: "Material Symbols Rounded Bold",
    postscript_name: "MaterialSymbolsRounded-Bold",
    preview: "/editor/fonts/google/previews/material-symbols-rounded-700.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/material-symbols-rounded/material-symbols-rounded-700.ttf",
    category: "monospace",
  },
  {
    id: "font_source-code-pro_regular",
    family: "Source Code Pro",
    full_name: "Source Code Pro Regular",
    postscript_name: "SourceCodePro",
    preview: "/editor/fonts/google/previews/source-code-pro-regular.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/source-code-pro/source-code-pro-regular.ttf",
    category: "monospace",
  },
  {
    id: "font_source-code-pro_600",
    family: "Source Code Pro",
    full_name: "Source Code Pro SemiBold",
    postscript_name: "SourceCodePro-SemiBold",
    preview: "/editor/fonts/google/previews/source-code-pro-600.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/source-code-pro/source-code-pro-600.ttf",
    category: "monospace",
  },
  {
    id: "font_source-code-pro_700",
    family: "Source Code Pro",
    full_name: "Source Code Pro Bold",
    postscript_name: "SourceCodePro-Bold",
    preview: "/editor/fonts/google/previews/source-code-pro-700.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/source-code-pro/source-code-pro-700.ttf",
    category: "monospace",
  },
  {
    id: "font_ibm-plex-mono_regular",
    family: "IBM Plex Mono",
    full_name: "IBM Plex Mono Regular",
    postscript_name: "IBMPlexMono",
    preview: "/editor/fonts/google/previews/ibm-plex-mono-regular.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/ibm-plex-mono/ibm-plex-mono-regular.ttf",
    category: "monospace",
  },
  {
    id: "font_ibm-plex-mono_600",
    family: "IBM Plex Mono",
    full_name: "IBM Plex Mono SemiBold",
    postscript_name: "IBMPlexMono-SemiBold",
    preview: "/editor/fonts/google/previews/ibm-plex-mono-600.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/ibm-plex-mono/ibm-plex-mono-600.ttf",
    category: "monospace",
  },
  {
    id: "font_ibm-plex-mono_700",
    family: "IBM Plex Mono",
    full_name: "IBM Plex Mono Bold",
    postscript_name: "IBMPlexMono-Bold",
    preview: "/editor/fonts/google/previews/ibm-plex-mono-700.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/ibm-plex-mono/ibm-plex-mono-700.ttf",
    category: "monospace",
  },
  {
    id: "font_jetbrains-mono_regular",
    family: "JetBrains Mono",
    full_name: "JetBrains Mono Regular",
    postscript_name: "JetBrainsMono",
    preview: "/editor/fonts/google/previews/jetbrains-mono-regular.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/jetbrains-mono/jetbrains-mono-regular.ttf",
    category: "monospace",
  },
  {
    id: "font_jetbrains-mono_600",
    family: "JetBrains Mono",
    full_name: "JetBrains Mono SemiBold",
    postscript_name: "JetBrainsMono-SemiBold",
    preview: "/editor/fonts/google/previews/jetbrains-mono-600.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/jetbrains-mono/jetbrains-mono-600.ttf",
    category: "monospace",
  },
  {
    id: "font_jetbrains-mono_700",
    family: "JetBrains Mono",
    full_name: "JetBrains Mono Bold",
    postscript_name: "JetBrainsMono-Bold",
    preview: "/editor/fonts/google/previews/jetbrains-mono-700.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/jetbrains-mono/jetbrains-mono-700.ttf",
    category: "monospace",
  },
  {
    id: "font_fira-code_regular",
    family: "Fira Code",
    full_name: "Fira Code Regular",
    postscript_name: "FiraCode",
    preview: "/editor/fonts/google/previews/fira-code-regular.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/fira-code/fira-code-regular.ttf",
    category: "monospace",
  },
  {
    id: "font_fira-code_600",
    family: "Fira Code",
    full_name: "Fira Code SemiBold",
    postscript_name: "FiraCode-SemiBold",
    preview: "/editor/fonts/google/previews/fira-code-600.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/fira-code/fira-code-600.ttf",
    category: "monospace",
  },
  {
    id: "font_fira-code_700",
    family: "Fira Code",
    full_name: "Fira Code Bold",
    postscript_name: "FiraCode-Bold",
    preview: "/editor/fonts/google/previews/fira-code-700.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/fira-code/fira-code-700.ttf",
    category: "monospace",
  },
  {
    id: "font_material-symbols-sharp_regular",
    family: "Material Symbols Sharp",
    full_name: "Material Symbols Sharp Regular",
    postscript_name: "MaterialSymbolsSharp",
    preview: "/editor/fonts/google/previews/material-symbols-sharp-regular.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/material-symbols-sharp/material-symbols-sharp-regular.ttf",
    category: "monospace",
  },
  {
    id: "font_material-symbols-sharp_600",
    family: "Material Symbols Sharp",
    full_name: "Material Symbols Sharp SemiBold",
    postscript_name: "MaterialSymbolsSharp-SemiBold",
    preview: "/editor/fonts/google/previews/material-symbols-sharp-600.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/material-symbols-sharp/material-symbols-sharp-600.ttf",
    category: "monospace",
  },
  {
    id: "font_material-symbols-sharp_700",
    family: "Material Symbols Sharp",
    full_name: "Material Symbols Sharp Bold",
    postscript_name: "MaterialSymbolsSharp-Bold",
    preview: "/editor/fonts/google/previews/material-symbols-sharp-700.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/material-symbols-sharp/material-symbols-sharp-700.ttf",
    category: "monospace",
  },
  {
    id: "font_overpass-mono_regular",
    family: "Overpass Mono",
    full_name: "Overpass Mono Regular",
    postscript_name: "OverpassMono",
    preview: "/editor/fonts/google/previews/overpass-mono-regular.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/overpass-mono/overpass-mono-regular.ttf",
    category: "monospace",
  },
  {
    id: "font_overpass-mono_600",
    family: "Overpass Mono",
    full_name: "Overpass Mono SemiBold",
    postscript_name: "OverpassMono-SemiBold",
    preview: "/editor/fonts/google/previews/overpass-mono-600.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/overpass-mono/overpass-mono-600.ttf",
    category: "monospace",
  },
  {
    id: "font_overpass-mono_700",
    family: "Overpass Mono",
    full_name: "Overpass Mono Bold",
    postscript_name: "OverpassMono-Bold",
    preview: "/editor/fonts/google/previews/overpass-mono-700.png",
    style: "normal",
    url: "/editor/fonts/google/ttf/overpass-mono/overpass-mono-700.ttf",
    category: "monospace",
  },
]

const textComponent1 = {
  id: "8_rxQGqFj-sJWchXvBM49",
  layers: [
    {
      angle: 0,
      stroke: null,
      strokeWidth: 0,
      left: 0,
      top: 0,
      width: 573.06,
      height: 244.56,
      opacity: 1,
      originX: "left",
      originY: "top",
      scaleX: 1,
      scaleY: 1,
      type: "Group",
      flipX: false,
      flipY: false,
      skewX: 0,
      skewY: 0,
      shadow: null,
      visible: true,
      start: 0,
      stop: 10,
      objects: [
        {
          id: "3gfzP58He89jnBXlC4dNo",
          angle: 0,
          stroke: "#ffffff",
          strokeWidth: 0,
          left: -251.96,
          top: -122.28,
          width: 480,
          height: 103.96,
          opacity: 1,
          originX: "left",
          originY: "top",
          scaleX: 1,
          scaleY: 1,
          type: "StaticText",
          flipX: false,
          flipY: false,
          skewX: 0,
          skewY: 0,
          shadow: null,
          visible: true,
          start: 0,
          stop: 10,
          text: "Hola",
          fontSize: 92,
          fontFamily: "OpenSans-Light",
          textAlign: "center",
          fontURL:
            "https://fonts.gstatic.com/s/opensans/v27/memSYaGs126MiZpBA-UvWbX2vVnXBbObj2OVZyOOSr4dVJWUgsiH0C4nY1M2xLER.ttf",
          fill: "#000000",
          charSpacing: 0,
          template: "Hola",
          lineHeight: 1.16,
          metadata: {},
        },
        {
          id: "9941Rqfh4nreFT8MYkrZz",
          angle: 0,
          stroke: "#ffffff",
          strokeWidth: 0,
          left: -286.53,
          top: 18.32,
          width: 573.06,
          height: 103.96,
          opacity: 1,
          originX: "left",
          originY: "top",
          scaleX: 1,
          scaleY: 1,
          type: "StaticText",
          flipX: false,
          flipY: false,
          skewX: 0,
          skewY: 0,
          shadow: null,
          visible: true,
          start: 0,
          stop: 10,
          text: "Amiguitos",
          fontSize: 92,
          fontFamily: "OpenSans-Medium",
          textAlign: "center",
          fontURL:
            "https://fonts.gstatic.com/s/opensans/v27/memSYaGs126MiZpBA-UvWbX2vVnXBbObj2OVZyOOSr4dVJWUgsjr0C4nY1M2xLER.ttf",
          fill: "#000000",
          charSpacing: 0,
          lineHeight: 1.16,
          metadata: {},
        },
      ],
    },
  ],
  metadata: {
    category: "single",
    types: ["StaticText"],
  },
  preview: "https://ik.imagekit.io/scenify/bdj0qkh18v4Zx06ZoMbGWb2O.png",
  userId: "_O8L0WDPlpKhDXspugZe3",
}

const textComponent2 = {
  id: "CN3w326wV9VUbq-CMkRxQ",
  layers: [
    {
      id: "CN3w326wV9VUbq-CMkRxQ",
      angle: 0,
      stroke: "#ffffff",
      strokeWidth: 0,
      left: 0,
      top: 0,
      width: 363.87,
      height: 107.4,
      opacity: 1,
      originX: "left",
      originY: "top",
      scaleX: 1,
      scaleY: 1,
      type: "StaticText",
      flipX: false,
      flipY: false,
      skewX: 0,
      skewY: 0,
      shadow: {
        color: "#000000",
        blur: 25,
        offsetX: 10,
        offsetY: 10,
        affectStroke: false,
        nonScaling: false,
      },
      visible: true,
      start: 0,
      stop: 10,
      text: "Sample text with shadow",
      fontSize: 44,
      fontFamily: "OpenSans-Light",
      textAlign: "center",
      fontStyle: "normal",
      fontURL:
        "https://fonts.gstatic.com/s/opensans/v27/memSYaGs126MiZpBA-UvWbX2vVnXBbObj2OVZyOOSr4dVJWUgsiH0C4nY1M2xLER.ttf",
      fill: "#000000",
      fontWeight: "normal",
      charSpacing: 0,
      template: "Sample text with shadow",
      lineHeight: 1.16,
    },
  ],
  metadata: {
    category: "single",
    types: ["StaticText"],
  },
  preview: "https://ik.imagekit.io/scenify/lJaXfdYQMHysY8VwUkWcIgqd.png",
  userId: "_O8L0WDPlpKhDXspugZe3",
}
export const textComponents = []

export const sampleFrames = [
  // {
  //   id: 10,
  //   name: "Twitter Post",
  //   width: 1200,
  //   height: 675,
  //   unit: "px",
  //   preview: "https://ik.imagekit.io/scenify/social-twittter-post.svg",
  // },
]

const layers: ILayer[] = []

const graphicTemplate = {
  id: "",
  name: "",
  type: "GRAPHIC",
  frame: {},
  content: [...layers],
}
