export const graphics = [
  "https://invalbum.com/editor/data/border-001-01.svg",
  "https://invalbum.com/editor/data/border-002-01.svg",
  "https://invalbum.com/editor/data/border-003-01.svg",
  "https://invalbum.com/editor/data/border-004-01.svg",
  "https://invalbum.com/editor/data/border-005-01.svg",
  "https://invalbum.com/editor/data/border-006-01.svg",
  "https://invalbum.com/editor/data/border-007-01.svg",
  "https://invalbum.com/editor/data/border-008-01.svg",
  "https://invalbum.com/editor/data/border-009-01.svg",
  "https://invalbum.com/editor/data/border-010-01.svg",
  "https://invalbum.com/editor/data/border-011-01.svg",
  "https://invalbum.com/editor/data/border-012-01.svg",
  "https://invalbum.com/editor/data/border-013-01.svg",
]

export const vectors = [
  "https://invalbum.com/editor/data/001.svg",
  "https://invalbum.com/editor/data/002.svg",
  "https://invalbum.com/editor/data/003.svg",
  "https://invalbum.com/editor/data/004.svg",
  "https://invalbum.com/editor/data/005.svg",
  "https://invalbum.com/editor/data/006.svg",
  "https://invalbum.com/editor/data/007.svg",
  "https://invalbum.com/editor/data/008.svg",
  "https://invalbum.com/editor/data/009.svg",
  "https://invalbum.com/editor/data/010.svg",
  "https://invalbum.com/editor/data/011.svg",
  "https://invalbum.com/editor/data/012.svg",
  "https://invalbum.com/editor/data/013.svg",
  "https://invalbum.com/editor/data/014.svg",
  "https://invalbum.com/editor/data/015.svg",
  "https://invalbum.com/editor/data/016.svg",
  "https://invalbum.com/editor/data/017.svg",
  "https://invalbum.com/editor/data/018.svg",
  "https://invalbum.com/editor/data/019.svg",
  "https://invalbum.com/editor/data/020.svg",
  "https://invalbum.com/editor/data/021.svg",
  "https://invalbum.com/editor/data/022.svg",
  "https://invalbum.com/editor/data/023.svg",
  "https://invalbum.com/editor/data/024.svg",
  "https://invalbum.com/editor/data/025.svg",
  "https://invalbum.com/editor/data/026.svg",
  "https://invalbum.com/editor/data/027.svg",
  "https://invalbum.com/editor/data/028.svg",
  "https://invalbum.com/editor/data/029.svg",
  "https://invalbum.com/editor/data/030.svg",
  "https://invalbum.com/editor/data/031.svg",
  "https://invalbum.com/editor/data/032.svg",
  "https://invalbum.com/editor/data/033.svg",
  "https://invalbum.com/editor/data/034.svg",
  "https://invalbum.com/editor/data/035.svg",
  "https://invalbum.com/editor/data/036.svg",
  "https://invalbum.com/editor/data/037.svg",
  "https://invalbum.com/editor/data/038.svg",
  "https://invalbum.com/editor/data/039.svg",
  "https://invalbum.com/editor/data/040.svg",
  "https://invalbum.com/editor/data/041.svg",
  "https://invalbum.com/editor/data/042.svg",
  "https://invalbum.com/editor/data/043.svg",
  "https://invalbum.com/editor/data/044.svg",
  "https://invalbum.com/editor/data/045.svg",
  "https://invalbum.com/editor/data/046.svg",
  "https://invalbum.com/editor/data/047.svg",
  "https://invalbum.com/editor/data/048.svg",
  "https://invalbum.com/editor/data/049.svg",
  "https://invalbum.com/editor/data/050.svg",
  "https://invalbum.com/editor/data/051.svg",
  "https://invalbum.com/editor/data/052.svg",
  "https://invalbum.com/editor/data/053.svg",
  "https://invalbum.com/editor/data/054.svg",
  "https://invalbum.com/editor/data/055.svg",
  "https://invalbum.com/editor/data/056.svg",
  "https://invalbum.com/editor/data/057.svg",
  "https://invalbum.com/editor/data/058.svg",
  "https://invalbum.com/editor/data/059.svg",
  "https://invalbum.com/editor/data/060.svg",
  "https://invalbum.com/editor/data/061.svg",
  "https://invalbum.com/editor/data/062.svg",
  "https://invalbum.com/editor/data/063.svg",
  "https://invalbum.com/editor/data/064.svg",
  "https://invalbum.com/editor/data/065.svg",
  "https://invalbum.com/editor/data/066.svg",
  "https://invalbum.com/editor/data/067.svg",
]

export const elements = [
  "https://invalbum.com/editor/data/border-001-01.svg",
  "https://invalbum.com/editor/data/border-002-01.svg",
  "https://invalbum.com/editor/data/border-003-01.svg",
  "https://invalbum.com/editor/data/border-004-01.svg",
  "https://invalbum.com/editor/data/border-005-01.svg",
  "https://invalbum.com/editor/data/border-006-01.svg",
  "https://invalbum.com/editor/data/border-007-01.svg",
  "https://invalbum.com/editor/data/border-008-01.svg",
  "https://invalbum.com/editor/data/border-009-01.svg",
  "https://invalbum.com/editor/data/border-010-01.svg",
  "https://invalbum.com/editor/data/border-011-01.svg",
  "https://invalbum.com/editor/data/border-012-01.svg",
  "https://invalbum.com/editor/data/border-013-01.svg",
  "https://invalbum.com/editor/data/line-001.svg",
  "https://invalbum.com/editor/data/line-002.svg",
  "https://invalbum.com/editor/data/line-003.svg",
  "https://invalbum.com/editor/data/line-004.svg",
  "https://invalbum.com/editor/data/line-005.svg",
  "https://invalbum.com/editor/data/line-006.svg",
  "https://invalbum.com/editor/data/line-007.svg",
  "https://invalbum.com/editor/data/line-008.svg",
  "https://invalbum.com/editor/data/line-009.svg",
  "https://invalbum.com/editor/data/line-010.svg",
  "https://invalbum.com/editor/data/line-011.svg",
  "https://invalbum.com/editor/data/line-012.svg",
  "https://invalbum.com/editor/data/line-013.svg",
  "https://invalbum.com/editor/data/line-014.svg",
  "https://invalbum.com/editor/data/line-015.svg",
  "https://invalbum.com/editor/data/line-016.svg",
  "https://invalbum.com/editor/data/line-017.svg",
  "https://invalbum.com/editor/data/line-018.svg",
  "https://invalbum.com/editor/data/line-019.svg",
  "https://invalbum.com/editor/data/line-020.svg",
  "https://invalbum.com/editor/data/line-021.svg",
  "https://invalbum.com/editor/data/line-022.svg",
  "https://invalbum.com/editor/data/line-023.svg",
  "https://invalbum.com/editor/data/line-024.svg",
  "https://invalbum.com/editor/data/line-025.svg",
  "https://invalbum.com/editor/data/line-026.svg",
  "https://invalbum.com/editor/data/line-027.svg",
  "https://invalbum.com/editor/data/line-028.svg",
  "https://invalbum.com/editor/data/line-029.svg",
  "https://invalbum.com/editor/data/line-030.svg",
  "https://invalbum.com/editor/data/line-031.svg",
  "https://invalbum.com/editor/data/line-032.svg",
  "https://invalbum.com/editor/data/line-033.svg",
  "https://invalbum.com/editor/data/line-034.svg",
  "https://invalbum.com/editor/data/line-035.svg",
  "https://invalbum.com/editor/data/line-036.svg",
  "https://invalbum.com/editor/data/line-037.svg",
  "https://invalbum.com/editor/data/line-038.svg",
  "https://invalbum.com/editor/data/line-039.svg",
  "https://invalbum.com/editor/data/line-040.svg",
  "https://invalbum.com/editor/data/line-041.svg",
  "https://invalbum.com/editor/data/line-042.svg",
  "https://invalbum.com/editor/data/line-043.svg",
  "https://invalbum.com/editor/data/line-044.svg",
  "https://invalbum.com/editor/data/line-045.svg",
  "https://invalbum.com/editor/data/line-046.svg",
  "https://invalbum.com/editor/data/line-047.svg",
  "https://invalbum.com/editor/data/line-048.svg",
  "https://invalbum.com/editor/data/line-049.svg",
  "https://invalbum.com/editor/data/line-050.svg",
  "https://invalbum.com/editor/data/line-051.svg",
]

// export const lines = [
//   "https://invalbum.com/editor/data/line-001.svg",
//   "https://invalbum.com/editor/data/line-002.svg",
//   "https://invalbum.com/editor/data/line-003.svg",
//   "https://invalbum.com/editor/data/line-004.svg",
//   "https://invalbum.com/editor/data/line-005.svg",
//   "https://invalbum.com/editor/data/line-006.svg",
//   "https://invalbum.com/editor/data/line-007.svg",
//   "https://invalbum.com/editor/data/line-008.svg",
//   "https://invalbum.com/editor/data/line-009.svg",
//   "https://invalbum.com/editor/data/line-010.svg",
//   "https://invalbum.com/editor/data/line-011.svg",
//   "https://invalbum.com/editor/data/line-012.svg",
//   "https://invalbum.com/editor/data/line-013.svg",
//   "https://invalbum.com/editor/data/line-014.svg",
//   "https://invalbum.com/editor/data/line-015.svg",
//   "https://invalbum.com/editor/data/line-016.svg",
//   "https://invalbum.com/editor/data/line-017.svg",
//   "https://invalbum.com/editor/data/line-018.svg",
//   "https://invalbum.com/editor/data/line-019.svg",
//   "https://invalbum.com/editor/data/line-020.svg",
//   "https://invalbum.com/editor/data/line-021.svg",
//   "https://invalbum.com/editor/data/line-022.svg",
//   "https://invalbum.com/editor/data/line-023.svg",
//   "https://invalbum.com/editor/data/line-024.svg",
//   "https://invalbum.com/editor/data/line-025.svg",
//   "https://invalbum.com/editor/data/line-026.svg",
//   "https://invalbum.com/editor/data/line-027.svg",
//   "https://invalbum.com/editor/data/line-028.svg",
//   "https://invalbum.com/editor/data/line-029.svg",
//   "https://invalbum.com/editor/data/line-030.svg",
//   "https://invalbum.com/editor/data/line-031.svg",
//   "https://invalbum.com/editor/data/line-032.svg",
//   "https://invalbum.com/editor/data/line-033.svg",
//   "https://invalbum.com/editor/data/line-034.svg",
//   "https://invalbum.com/editor/data/line-035.svg",
//   "https://invalbum.com/editor/data/line-036.svg",
//   "https://invalbum.com/editor/data/line-037.svg",
//   "https://invalbum.com/editor/data/line-038.svg",
//   "https://invalbum.com/editor/data/line-039.svg",
//   "https://invalbum.com/editor/data/line-040.svg",
//   "https://invalbum.com/editor/data/line-041.svg",
//   "https://invalbum.com/editor/data/line-042.svg",
//   "https://invalbum.com/editor/data/line-043.svg",
//   "https://invalbum.com/editor/data/line-044.svg",
//   "https://invalbum.com/editor/data/line-045.svg",
//   "https://invalbum.com/editor/data/line-046.svg",
//   "https://invalbum.com/editor/data/line-047.svg",
//   "https://invalbum.com/editor/data/line-048.svg",
//   "https://invalbum.com/editor/data/line-049.svg",
//   "https://invalbum.com/editor/data/line-050.svg",
//   "https://invalbum.com/editor/data/line-051.svg",
// ]
export const images = []
export const pixabayImages = []
export const lines= [];